#!/usr/bin/env python3
"""Generate the public project README from the current output catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.parse import quote

REPOSITORY = "anonymouskeys/Free-configs-"
BRANCH = "main"
TELEGRAM_URL = "https://t.me/anonymouskeys"
TON_ADDRESS = "UQCeZHtAYYkCOeJW26HkXgdT4fG9f9m6m-3oQanpd4bpyrEG"
USDT_TRC20_ADDRESS = "TYUFWzRdicVgUgAf5HCPTVGHr6J7p2Kxrf"

COUNTRY_NAMES = {
    "ae": "🇦🇪 United Arab Emirates", "ar": "🇦🇷 Argentina", "at": "🇦🇹 Austria",
    "au": "🇦🇺 Australia", "be": "🇧🇪 Belgium", "bg": "🇧🇬 Bulgaria",
    "br": "🇧🇷 Brazil", "ca": "🇨🇦 Canada", "ch": "🇨🇭 Switzerland",
    "cl": "🇨🇱 Chile", "cn": "🇨🇳 China", "cz": "🇨🇿 Czechia",
    "de": "🇩🇪 Germany", "dk": "🇩🇰 Denmark", "ee": "🇪🇪 Estonia",
    "es": "🇪🇸 Spain", "fi": "🇫🇮 Finland", "fr": "🇫🇷 France",
    "gb": "🇬🇧 United Kingdom", "gr": "🇬🇷 Greece", "hk": "🇭🇰 Hong Kong",
    "hr": "🇭🇷 Croatia", "hu": "🇭🇺 Hungary", "id": "🇮🇩 Indonesia",
    "ie": "🇮🇪 Ireland", "il": "🇮🇱 Israel", "in": "🇮🇳 India",
    "is": "🇮🇸 Iceland", "it": "🇮🇹 Italy", "jp": "🇯🇵 Japan",
    "kr": "🇰🇷 South Korea", "kz": "🇰🇿 Kazakhstan", "lt": "🇱🇹 Lithuania",
    "lu": "🇱🇺 Luxembourg", "lv": "🇱🇻 Latvia", "md": "🇲🇩 Moldova",
    "mx": "🇲🇽 Mexico", "my": "🇲🇾 Malaysia", "nl": "🇳🇱 Netherlands",
    "no": "🇳🇴 Norway", "nz": "🇳🇿 New Zealand", "ph": "🇵🇭 Philippines",
    "pl": "🇵🇱 Poland", "pt": "🇵🇹 Portugal", "ro": "🇷🇴 Romania",
    "rs": "🇷🇸 Serbia", "ru": "🇷🇺 Russia", "se": "🇸🇪 Sweden",
    "sg": "🇸🇬 Singapore", "si": "🇸🇮 Slovenia", "sk": "🇸🇰 Slovakia",
    "th": "🇹🇭 Thailand", "tr": "🇹🇷 Türkiye", "tw": "🇹🇼 Taiwan",
    "ua": "🇺🇦 Ukraine", "unknown": "🌍 Unknown", "us": "🇺🇸 United States",
    "vn": "🇻🇳 Vietnam", "za": "🇿🇦 South Africa",
}

PROTOCOL_NAMES = {
    "vless": "VLESS", "vmess": "VMess", "trojan": "Trojan",
    "ss": "Shadowsocks", "hysteria": "Hysteria / Hysteria 2",
    "hysteria2": "Hysteria 2",
}
TRANSPORT_NAMES = {
    "grpc": "gRPC", "http": "HTTP", "httpupgrade": "HTTP Upgrade",
    "quic": "QUIC", "raw": "RAW", "reality": "REALITY",
    "reality-vision": "REALITY Vision", "splithttp": "SplitHTTP",
    "tcp": "TCP", "unknown": "Unknown", "ws": "WebSocket", "xhttp": "XHTTP",
}


def count_lines(path: Path) -> int:
    if not path.is_file():
        return 0
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        return sum(1 for line in handle if line.strip())


def raw_url(relative_path: str) -> str:
    encoded = "/".join(quote(part) for part in relative_path.split("/"))
    return f"https://raw.githubusercontent.com/{REPOSITORY}/{BRANCH}/{encoded}"


def subscription_row(label: str, relative_path: str, count: int) -> str:
    return f"| {label} | `{count:,}` | [Copy subscription]({raw_url(relative_path)}) |"


def category_rows(output_dir: Path, folder: str, labels: dict[str, str]) -> list[str]:
    directory = output_dir / folder
    rows: list[str] = []
    if not directory.is_dir():
        return rows
    for path in sorted(directory.glob("*.txt")):
        key = path.stem
        label = labels.get(key, key.replace("-", " ").title())
        rows.append(subscription_row(label, f"output/{folder}/{path.name}", count_lines(path)))
    return rows


def generate_readme(output_dir: Path) -> str:
    status_path = output_dir / "status.json"
    status = json.loads(status_path.read_text(encoding="utf-8")) if status_path.is_file() else {}
    summary = status.get("summary", {})
    updated = status.get("updated_at_utc", "Generated by the latest successful workflow run")
    total = int(summary.get("final_configs", count_lines(output_dir / "all.txt")))
    sources_ok = int(summary.get("successful_sources", 0))
    sources_total = int(summary.get("configured_sources", 0))

    protocol_rows = category_rows(output_dir, "protocol", PROTOCOL_NAMES)
    transport_rows = category_rows(output_dir, "transport", TRANSPORT_NAMES)
    country_rows = category_rows(output_dir, "countries", COUNTRY_NAMES)

    lines = [
        '<p align="center"><img src="assets/anonymouskeys-dragon.png" width="420" alt="Anonymous Keys dragon logo"></p>',
        "",
        '<h1 align="center">Anonymous Keys — Free Proxy Subscriptions</h1>',
        "",
        '<p align="center">Automatically collected, normalized, deduplicated and refreshed every four hours.</p>',
        "",
        f'<p align="center"><a href="{TELEGRAM_URL}"><strong>Join @anonymouskeys on Telegram</strong></a> for fresh subscriptions, updates and announcements.</p>',
        "",
        f"![Configurations](https://img.shields.io/badge/configurations-{total:,}-brightgreen)",
        f"![Sources](https://img.shields.io/badge/sources-{sources_ok}%2F{sources_total}-blue)",
        "![Update schedule](https://img.shields.io/badge/updated-every%204%20hours-purple)",
        "",
        "> [!IMPORTANT]",
        "> These public configurations are collected from third-party sources. Availability, speed and security are not guaranteed. Use them at your own risk and never send sensitive traffic through an untrusted server.",
        "",
        "## Quick subscription",
        "",
        "| Collection | Configurations | Subscription URL |",
        "|---|---:|---|",
        subscription_row("All configurations", "output/all.txt", total),
        "",
        "Copy the **Copy subscription** link address and paste it into a compatible client. The files contain one share URI per line.",
        "",
        "## Subscriptions by protocol",
        "",
        "| Protocol | Configurations | Subscription URL |",
        "|---|---:|---|",
        *protocol_rows,
        "",
        "## Subscriptions by transport and security",
        "",
        "| Category | Configurations | Subscription URL |",
        "|---|---:|---|",
        *transport_rows,
        "",
        "## Subscriptions by location",
        "",
        "Country classification is inferred only from profile labels supplied by the sources. No GeoIP, DNS lookup or external location API is used.",
        "",
        "<details>",
        f"<summary><strong>Show all {len(country_rows)} location subscriptions</strong></summary>",
        "",
        "| Location | Configurations | Subscription URL |",
        "|---|---:|---|",
        *country_rows,
        "",
        "</details>",
        "",
        "## Current statistics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Last successful update | `{updated}` |",
        f"| Configured sources | `{sources_total:,}` |",
        f"| Successful sources | `{sources_ok:,}` |",
        f"| Failed sources | `{int(summary.get('failed_sources', 0)):,}` |",
        f"| Downloaded / parsed configurations | `{int(summary.get('input_configs', 0)):,}` |",
        f"| Duplicate configurations removed | `{int(summary.get('duplicates_removed', 0)):,}` |",
        f"| Invalid configurations rejected | `{int(summary.get('invalid_configs', 0)):,}` |",
        f"| Published configurations | `{total:,}` |",
        "",
        "## Telegram community",
        "",
        f"Visit **[t.me/anonymouskeys]({TELEGRAM_URL})** and subscribe to the channel for project news, newly added sources and service updates.",
        "",
        "## Support Anonymous Keys",
        "",
        "If this project is useful to you, a donation is a simple way to say thank you and help keep the automation running.",
        "",
        "| TON | USDT (TRC20) |",
        "|---|---|",
        "| <img src=\"assets/donate-ton.jpg\" width=\"300\" alt=\"TON donation QR code\"> | <img src=\"assets/donate-usdt-trc20.jpg\" width=\"300\" alt=\"USDT TRC20 donation QR code\"> |",
        f"| `{TON_ADDRESS}` | `{USDT_TRC20_ADDRESS}` |",
        "",
        "> Send only assets supported by the indicated network. Transfers sent through the wrong network may be permanently lost.",
        "",
        "## How this repository works",
        "",
        "1. Private source URLs are read from GitHub Actions secrets and are never published.",
        "2. Subscriptions are downloaded, decoded, parsed and normalized.",
        "3. Duplicate and invalid entries are removed.",
        "4. Clean subscriptions are generated by protocol, transport/security and location.",
        "5. This README and all counters are regenerated from the published output on every successful run.",
        "",
        "---",
        "",
        f'<p align="center">Maintained by <a href="{TELEGRAM_URL}"><strong>@anonymouskeys</strong></a></p>',
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate README.md from output subscriptions")
    parser.add_argument("--output-dir", default="output")
    parser.add_argument("--readme", default="README.md")
    args = parser.parse_args()
    output_dir = Path(args.output_dir)
    try:
        content = generate_readme(output_dir)
        Path(args.readme).write_text(content, encoding="utf-8", newline="\n")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"README generation failed: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
